[id='dev-studio-install-proc']
= Installing and setting up Red Hat JBoss Developer Studio

Red Hat JBoss Developer Studio is the JBoss integrated development environment (IDE) based on Eclipse. Red Hat JBoss Developer Studio provides plug-ins with tools and interfaces for {PRODUCT}. 
.Prerequisites
{PRODUCT} is installed. Comment: only on EAP?

.Procedure
. Download the latest Red Hat JBoss Developer Studio:
.. Log in to the https://access.redhat.com[Red Hat Customer Portal].
.. Click *DOWNLOADS* at the top of the page.
.. On the *Product Downloads* page that opens, navigate to the JBOSS DEVELOPMENT AND MANAGEMENT section, and click *Red Hat JBoss Developer Studio*.
.. On the *Software Downloads* page, download *Red Hat JBoss Developer Studio 11.3.0 Stand-alone Installer*.
. Install and configure JBoss Developer Studio as described in the https://access.redhat.com/documentation/en-us/red_hat_jboss_developer_studio/11.3/html-single/installation_guide[_Red Hat JBoss Developer Studio Installation Guide_].
. Install the Red Hat JBoss Developer Studio plug-ins, as described in this document.

[IMPORTANT]
==== 
Because of an issue in the way multi-byte rule names are handled, you must ensure that the instance of Red Hat JBoss Developer Studio is started with the file encoding set to `UTF-8`. You can do this by editing the `$_JBDS_HOME_/studio/devstudio.ini` file and adding the following property: `"-Dfile.encoding=UTF-8"`.
====

