[id='dev-studio-plug-in-install-proc']
= Installing Red Hat JBoss Developer Studio plug-ins

Red Hat JBoss Developer Studio provides plug-ins with tools and interfaces for {PRODUCT}. The plug-ins are based on the community version of the plug-ins . For this reason, the {PRODUCT} plug-in is called the Drools plug-in.

Get the latest Red Hat JBoss Developer Studio from the https://access.redhat.com[Red Hat Customer Portal]. The {PRODUCT} plug-ins for Red Hat JBoss Developer Studio are available using the update site.

.Procedure
. Download the {PRODUCT} plug-ins for Red Hat JBoss Developer Studio:
.. Log in to the https://access.redhat.com[Red Hat Customer Portal].
.. Click *DOWNLOADS* at the top of the page.
.. On the *Product Downloads* page that opens, navigate to the JBOSS DEVELOPMENT AND MANAGEMENT section, and click *Red Hat JBoss Developer Studio*.
.. On the *Software Downloads* page, download *Red Hat JBoss Developer Studio 11.3.0 Update Site Zip* (``).
. Start Red Hat JBoss Developer Studio.
. Click *Help* -> *Install New Software*.
. Click *Add* to enter the *Add Repository* menu.
. Provide a name next to the *Name* field and add the following URL in the *Location* field: `https://devstudio.jboss.com/11/stable/updates/integration-stack/`.
. Click *OK*.
. Select the *JBoss Business Process and Rule Development* feature from the available options, click *Next*, and then click *Next* again.
. Read the license and accept it by selecting the appropriate radio button, and click *Finish*.
. Restart Red Hat JBoss Developer Studio after the installation process finishes.
