[id='dm-server-configure-proc']
= Configuring the {PRODUCT} server

You can configure Red Hat JBoss Developer Studio to run the {PRODUCT} server.

.Prerequisite
* Red Hat JBoss Developer Studio in installed with the {PRODUCT} plug-ins.
* {Product} is installed.

.Procedure
. Start Red Hat JBoss Developer Studio.
. To open the Drools view, click *Window* -> *Perpective* -> *Open Perspective* -> *Other*, select *Drools*, and click *OK*.
. Click *Window* -> *Show View* -> *Other...* and select *Server* -> *Servers* to add the server view.
. Right click the *Servers* panel and select *New* -> *Server* to open the server menu.
. Click *Red Hat JBoss Middleware* -> *JBoss Enterprise Application Platform 7.1* and click *Next* to define the server.
. Click *Next* on the Create a new Server Adapter page.
. To set the home directory on the Jboss Runtime page, click the *Browse* button and navigate to the {EAP} directory where {PRODUCT} is installed.
. Enter a name for the server in the *Name* field, ensure that the configuration file is set, and click *Finish*.
