[id='cluster-custom-config-proc']

= Clustering {PRODUCT} on {EAP}

When using {EAP} clustering, a single {EAP} domain controller exists with other {EAP} slaves connecting to it as management users. You can deploy {CENTRAL} as a management user on a domain controller, and the WAR deployments will be distributed to other members of the {EAP} cluster.

.Prerequisite
You have a {EAP} cluster.

.Procedure

. Install the JDBC driver. 
. If you are clustering {KIE_SERVER}, edit the `_EAP_HOME_/_MODE_/configurationd/domain.xml` or `_EAP_HOME_/_MODE_/configurationd/standalone.xml` file.
.. Add the {KIE_SERVER} and EJB timer data sources to the `full` profile:
ifdef::PAM[]
* Add the following data source to allow {KIE_SERVER} to connect to the database:
+
[source,xml]
----
<xa-datasource jndi-name="java:/jboss/datasources/rhpam" pool-name="rhpam-RHPAM" use-java-context="true" enabled="true"> 
  <xa-datasource-property name="PortNumber">5432</xa-datasource-property> 
  <xa-datasource-property name="ServerName">myapp-postgresql</xa-datasource-property> 
  <driver>postgresql</driver> 
  <transaction-isolation>TRANSACTION_READ_COMMITTED</transaction-isolation> 
  <security>
    <user-name>rhpam</user-name> 
    <password>BBfPPb2!</password> 
</security> 
</xa-datasource>
----
* Add the following data source to enable the EJB timer:
+
[source,xml]
----
<xa-datasource jndi-name="java:jboss/datasources/ejb_timer" pool-name="ejb_timer-EJB_TIMER" use-java-context="true" enabled="true">
    <xa-datasource-property name="DatabaseName">rhpam7</xa-datasource-property> 
    <xa-datasource-property name="PortNumber">5432</xa-datasource-property> 
    <xa-datasource-property name="ServerName">myapp-postgresql</xa-datasource-property> 
    <driver>postgresql</driver> 
    <transaction-isolation>TRANSACTION_READ_COMMITTED</transaction-isolation> 
    <xa-pool> 
        <min-pool-size>10</min-pool-size> 
        <max-pool-size>10</max-pool-size> 
    </xa-pool> 
    <security> 
        <user-name>rhpam</user-name> 
        <password>BBfPPb2!</password> 
    </security> 
</xa-datasource>
----
.. Edit the datastore property:
+
[source,xml]
----
<data-stores>      
    <database-data-store name="ejb_timer-EJB_TIMER_ds" datasource-jndi-name="java:jboss/datasources/ejb_timer" database="postgresql" partition="ejb_timer-EJB_TIMER_part" refresh-interval="30000"/>       
</data-stores> 
----

endif::PAM[]

. Define the data source driver.
+
.PostgreSQL Driver Definition
====
[source,xml]
----
<driver name="postgres" module="org.postgresql">
  <xa-datasource-class>org.postgresql.xa.PGXADataSource</xa-datasource-class>
</driver>
----
====
+
Ensure that the data sources contain schemas. If your data source does not contain schemas, ensure your nodes start one at a time.
. Open `_EAP_HOME_/domain/business-central.war/WEB-INF/classes/META-INF/persistence.xml` and change the property `hibernate.hbm2ddl.auto="update"` to `hibernate.hbm2ddl.auto="none"`.

. Configure individual server nodes in the `main-server-group` element in the `_EAP_HOME_/domain/configuration/domain.xml` file with properties defined in
ifdef::PAM[]
<<_cluster_properties_BPMS>>.
endif::PAM[]
ifdef::DM[]
<<_cluster_properties_BRMS>>.
endif::DM[]

ifdef::PAM[]
+
[id='_cluster_properties_BPMS']
.Cluster Node Properties
[cols="1,1,2", frame="all", options="header"]
|===
|Property Name
|Value
|Description

|jboss.node.name
|nodeOne
|Node name unique within the cluster.


|org.uberfire.cluster.id
|bpms-cluster
|Helix cluster name.

|org.uberfire.cluster.local.id
|nodeOne_12345
|Unique ID of the Helix cluster node. Note that `:` is replaced with `_`.

|org.uberfire.cluster.vfs.lock
|vfs-repo
|Name of the resource defined on the Helix cluster.

|org.uberfire.metadata.index.dir
|/home/jbpm/node[N]/index
|Location where the index for search is to be created (maintained by Apache Lucene).

|org.uberfire.nio.git.daemon.host
|nodeOne
|The name of the daemon host machine in a physical cluster.

|org.uberfire.nio.git.daemon.port
|9418
|Port used by the VFS repo to accept client connections. The port must be unique for each cluster member.

|org.uberfire.nio.git.dir
|/home/jbpm/node[N]/repo
|Git (VFS) repository location on node[N].

|org.uberfire.nio.git.ssh.host
|nodeOne
|The name of the SSH host machine in a physical cluster.

|org.uberfire.nio.git.ssh.port
|8003
|The unique port number for ssh access to the GIT repo for a cluster running on physical machines.

|org.uberfire.nio.git.ssh.hostport and org.uberfire.nio.git.daemon.hostport
|8003 and 9418
|In a virtualized environment, the outside port to be used.
|===
endif::PAM[]
ifdef::DM[]
+
[id='_cluster_properties_BRMS']
.Cluster Node Properties
[cols="1,1,2", frame="all", options="header"]
|===
|Property Name
|Value
|Description

|org.uberfire.nio.git.dir
|/home/jbrm/node[N]/repo
|Git (VFS) repository location on node[N].

|jboss.node.name
|nodeOne
|Node name unique within the cluster.

|org.uberfire.cluster.id
|brms-cluster
|Helix cluster name.

|org.uberfire.cluster.local.id
|nodeOne_12345
|Unique ID of the Helix cluster node. Note that `:` is replaced with `_`.

|org.uberfire.cluster.vfs.lock
|vfs-repo
|Name of the resource defined on the Helix cluster.

|org.uberfire.nio.git.daemon.port
|9418
|Port used by the VFS repo to accept client connections. The port must be unique for each cluster member.

|org.uberfire.metadata.index.dir
|/home/jbrm/node[N]/index
|Location where the index for search is to be created (maintained by Apache Lucene).

|org.uberfire.nio.git.ssh.port
|8003
|The unique port number for ssh access to the Git repo for a cluster running on physical machines.

|org.uberfire.nio.git.daemon.host
|nodeOne
|The name of the daemon host machine in a physical cluster.

|org.uberfire.nio.git.ssh.host
|nodeOne
|The name of the SSH host machine in a physical cluster.

|org.uberfire.nio.git.ssh.hostport and org.uberfire.nio.git.daemon.hostport
|8003 and 9418
|In a virtualized environment, the outside port to be used.
|===
endif::DM[]

ifdef::PAM[]
+
.Cluster nodeOne Configuration
====
[source,xml]
----
<system-properties>
  <property name="org.uberfire.nio.git.dir" value="/tmp/bpms/nodeone"
            boot-time="false"/>
  <property name="jboss.node.name" value="nodeOne" boot-time="false"/>
  <property name="org.uberfire.cluster.id" value="bpms-cluster" boot-time="false"/>
  <property name="org.uberfire.cluster.zk"
            value="server1:2181,server2:2182,server3:2183" boot-time="false"/>
  <property name="org.uberfire.cluster.local.id" value="nodeOne_12345"
            boot-time="false"/>
  <property name="org.uberfire.cluster.vfs.lock" value="vfs-repo" boot-time="false"/>
  <property name="org.uberfire.nio.git.daemon.host" value="nodeOne"/>
  <property name="org.uberfire.nio.git.daemon.port" value="9418" boot-time="false"/>
  <property name="org.uberfire.nio.git.daemon.hostport" value="9418"
            boot-time="false"/>
  <property name="org.uberfire.nio.git.ssh.port" value="8003" boot-time="false"/>
  <property name="org.uberfire.nio.git.ssh.hostport" value="8003" boot-time="false"/>
  <property name="org.uberfire.nio.git.ssh.host" value="nodeOne"/>
  <property name="org.uberfire.metadata.index.dir" value="/tmp/jbpm/nodeone"
            boot-time="false"/>
  <property name="org.uberfire.nio.git.ssh.cert.dir" value="/tmp/jbpm/nodeone"
            boot-time="false"/>
</system-properties>
----
====
endif::PAM[]
ifdef::PAM[]
+
.Cluster nodeTwo Configuration
====
[source,xml]
----
<system-properties>
  <property name="org.uberfire.nio.git.dir" value="/tmp/bpms/nodetwo"
            boot-time="false"/>
  <property name="jboss.node.name" value="nodeTwo" boot-time="false"/>
  <property name="org.uberfire.cluster.id" value="bpms-cluster" boot-time="false"/>
  <property name="org.uberfire.cluster.zk"
            value="server1:2181,server2:2182,server3:2183" boot-time="false"/>
  <property name="org.uberfire.cluster.local.id" value="nodeTwo_12346"
            boot-time="false"/>
  <property name="org.uberfire.cluster.vfs.lock" value="vfs-repo" boot-time="false"/>
  <property name="org.uberfire.nio.git.daemon.host" value="nodeTwo" />
  <property name="org.uberfire.nio.git.daemon.port" value="9419" boot-time="false"/>
  <property name="org.uberfire.nio.git.daemon.hostport" value="9419"
            boot-time="false"/>
  <property name="org.uberfire.nio.git.ssh.port" value="8004" boot-time="false"/>
  <property name="org.uberfire.nio.git.ssh.hostport" value="8004" boot-time="false"/>
  <property name="org.uberfire.nio.git.ssh.host" value="nodeTwo" />
  <property name="org.uberfire.metadata.index.dir" value="/tmp/jbpm/nodetwo"
            boot-time="false"/>
  <property name="org.uberfire.nio.git.ssh.cert.dir" value="/tmp/jbpm/nodetwo"
            boot-time="false"/>
</system-properties>
----
====
endif::PAM[]
ifdef::PAM[]
+
.Cluster nodeThree Configuration
====
[source,xml]
----
<system-properties>
  <property name="org.uberfire.nio.git.dir" value="/tmp/bpms/nodethree"
            boot-time="false"/>
  <property name="jboss.node.name" value="nodeThree" boot-time="false"/>
  <property name="org.uberfire.cluster.id" value="bpms-cluster" boot-time="false"/>
  <property name="org.uberfire.cluster.zk"
            value="server1:2181,server2:2182,server3:2183" boot-time="false"/>
  <property name="org.uberfire.cluster.local.id" value="nodeThree_12347"
            boot-time="false"/>
  <property name="org.uberfire.cluster.vfs.lock" value="vfs-repo" boot-time="false"/>
  <property name="org.uberfire.nio.git.daemon.host" value="nodeThree" />
  <property name="org.uberfire.nio.git.daemon.port" value="9420" boot-time="false"/>
  <property name="org.uberfire.nio.git.daemon.hostport" value="9420"
            boot-time="false"/>
  <property name="org.uberfire.nio.git.ssh.port" value="8005" boot-time="false"/>
  <property name="org.uberfire.nio.git.ssh.hostport" value="8005" boot-time="false"/>
  <property name="org.uberfire.nio.git.ssh.host" value="nodeThree" />
  <property name="org.uberfire.metadata.index.dir" value="/tmp/jbpm/nodethree"
            boot-time="false"/>
  <property name="org.uberfire.nio.git.ssh.cert.dir" value="/tmp/jbpm/nodethree"
            boot-time="false"/>
</system-properties>
----
====
endif::PAM[]
ifdef::DM[]
+
.Cluster nodeOne Configuration
====
[source,xml]
----
<system-properties>
  <property name="org.uberfire.nio.git.dir" value="/tmp/brms/nodeone"
            boot-time="false"/>
  <property name="jboss.node.name" value="nodeOne" boot-time="false"/>
  <property name="org.uberfire.cluster.id" value="brms-cluster" boot-time="false"/>
  <property name="org.uberfire.cluster.zk"
            value="server1:2181,server2:2181,server3:2181" boot-time="false"/>
  <property name="org.uberfire.cluster.local.id" value="nodeOne_12345"
            boot-time="false"/>
  <property name="org.uberfire.cluster.vfs.lock" value="vfs-repo" boot-time="false"/>
  <property name="org.uberfire.nio.git.daemon.port" value="9418" boot-time="false"/>
  <property name="org.uberfire.metadata.index.dir" value="/tmp/jbrm/nodeone"
            boot-time="false"/>
  <property name="org.uberfire.nio.git.ssh.cert.dir" value="/tmp/jbpm/nodeone"
            boot-time="false"/>
  <property name="org.uberfire.nio.git.ssh.port" value="8003" boot-time="false"/>
  <property name="org.uberfire.nio.git.daemon.host" value="nodeOne" />
  <property name="org.uberfire.nio.git.ssh.host" value="nodeOne" />
  <property name="org.uberfire.nio.git.ssh.hostport" value="8003" boot-time="false"/>
  <property name="org.uberfire.nio.git.daemon.hostport" value="9418"
            boot-time="false"/>
</system-properties>
----
====
endif::DM[]
ifdef::DM[]
+
.Cluster nodeTwo Configuration
====
[source,xml]
----
<system-properties>
  <property name="org.uberfire.nio.git.dir" value="/tmp/brms/nodetwo"
            boot-time="false"/>
  <property name="jboss.node.name" value="nodeTwo" boot-time="false"/>
  <property name="org.uberfire.cluster.id" value="brms-cluster" boot-time="false"/>
  <property name="org.uberfire.cluster.zk"
            value="server1:2181,server2:2182,server3:2183" boot-time="false"/>
  <property name="org.uberfire.cluster.local.id" value="nodeTwo_12346"
            boot-time="false"/>
  <property name="org.uberfire.cluster.vfs.lock" value="vfs-repo" boot-time="false"/>
  <property name="org.uberfire.nio.git.daemon.port" value="9418" boot-time="false"/>
  <property name="org.uberfire.metadata.index.dir" value="/tmp/jbrm/nodetwo"
            boot-time="false"/>
  <property name="org.uberfire.nio.git.ssh.cert.dir" value="/tmp/jbpm/nodetwo"
            boot-time="false"/>
  <property name="org.uberfire.nio.git.ssh.port" value="8003" boot-time="false"/>
  <property name="org.uberfire.nio.git.daemon.host" value="nodeTwo" />
  <property name="org.uberfire.nio.git.ssh.host" value="nodeTwo" />
  <property name="org.uberfire.nio.git.ssh.hostport" value="8003" boot-time="false"/>
  <property name="org.uberfire.nio.git.daemon.hostport" value="9418"
            boot-time="false"/>
</system-properties>
----
====
endif::DM[]
ifdef::DM[]
+
.Cluster nodeThree Configuration
====
[source,xml]
----
<system-properties>
  <property name="org.uberfire.nio.git.dir" value="/tmp/brms/nodethree"
            boot-time="false"/>
  <property name="jboss.node.name" value="nodeThree" boot-time="false"/>
  <property name="org.uberfire.cluster.id" value="brms-cluster" boot-time="false"/>
  <property name="org.uberfire.cluster.zk"
            value="server1:2181,server2:2182,server3:2183" boot-time="false"/>
  <property name="org.uberfire.cluster.local.id" value="nodeThree_12347"
            boot-time="false"/>
  <property name="org.uberfire.cluster.vfs.lock" value="vfs-repo" boot-time="false"/>
  <property name="org.uberfire.nio.git.daemon.port" value="9418" boot-time="false"/>
  <property name="org.uberfire.metadata.index.dir" value="/tmp/jbrm/nodethree"
            boot-time="false"/>
  <property name="org.uberfire.nio.git.ssh.cert.dir" value="/tmp/jbpm/nodethree"
            boot-time="false"/>
  <property name="org.uberfire.nio.git.ssh.port" value="8003" boot-time="false"/>
  <property name="org.uberfire.nio.git.daemon.host" value="nodeThree" />
  <property name="org.uberfire.nio.git.ssh.host" value="nodeThree" />
  <property name="org.uberfire.nio.git.ssh.hostport" value="8003" boot-time="false"/>
  <property name="org.uberfire.nio.git.daemon.hostport" value="9418"
            boot-time="false"/>
</system-properties>
----
====
endif::DM[]

. Add management users as instructed in the _Administration and Configuration Guide_ for {EAP} and application users as instructed in _{PRODUCT} Administration and Configuration Guide_.
// change on purpose - cd = change directory
. Change to `_EAP_HOME_/bin` and start the application server in domain mode:
+
On UNIX systems:
+
----
./domain.sh
----
+
On Windows:
+
----
./domain.bat
----

. Check that the nodes are available.

Deploy the {CENTRAL} application to your servers:

ifdef::PAM[]
. Change the predefined persistence of the application to the required database (PostgreSQL): in `persistence.xml` change the following:
+
.. `jta-data-source` name to the source defined on the application server (`java:jboss/datasources/psbpmsDS`).
.. Hibernate dialect to be match the data source dialect (`org.hibernate.dialect.PostgreSQLDialect`).

. Log in as the management user to the server *Administration* console of your domain and add the new deployments using the *Runtime view* of the console. Once the deployment is added to the domain, assign it to the correct server group (`main-server-group`).
endif::PAM[]

ifdef::DM[]
* Log in as the management user to the server *Administration* console of your domain and add the new deployments using the *Runtime view* of the console. Once the deployment is added to the domain, assign it to the correct server group (`main-server-group`).
endif::DM[]

[NOTE]
====
It is important users explicitly check deployment unit readiness with every cluster member.

When a deployment unit is created on a cluster node, it takes some time before it is distributed among all cluster members. Deployment status can be checked using the UI and REST, however, if the query goes to the node where the deployment was originally issued, the answer is `deployed`. Any request targeting this deployment unit sent to a different cluster member fails with `DeploymentNotFoundException`.
====

ifdef::PAM[]
[id='_exec_server']
