[id='clustering-headless-controller-proc']
= Clustering with the headless Process Automation Manager controller

You can configure {KIE_SERVER} to run in managed or unmanaged mode. If {KIE_SERVER} is unmanaged, you must manually create and maintain containers. If {KIE_SERVER} is managed, the Process Automation Manager controller manages the {KIE_SERVER} configuration and you interact with the controller to create and maintain containers.

The Process Automation Manager controller is integrated with {CENTRAL}. However, if you do not install {CENTRAL}, you can install the headless Process Automation Manager controller and use the REST API or the {KIE_SERVER} Java Client API to interact with it.

.Prerequisites
* A backed-up {EAP} installation version 7.1 or higher is available. The base directory of the {EAP} installation is referred to as `__EAP_HOME__`. 
* Sufficient user permissions to complete the installation are granted.

.Procedure
. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options:

* Product: {PRODUCT}
* Version: {PRODUCT_VERSION}
. Download *{PRODUCT} 7.0.0 Add Ons* (the `rhpam-7.0.0.GA-add-ons.zip` file).
. Unzip the `rhpam-7.0.0.GA-add-ons.zip` file. The `rhpam-7.0-controller-ee7.zip` file is in the unzipped directory.
. Extract the `rhpam-7.0-controller-ee7` archive to a temporary directory. In the following examples this directory is called `__TEMP_DIR__`.
. Copy the `__TEMP_DIR__/rhpam-7.0-controller-ee7/controller.war` directory to `__EAP_HOME__/standalone/deployments/`.
+
WARNING: Ensure the names of the headless Process Automation Manager controller deployments you are copying do not conflict with your existing deployments in the {EAP} instance.
. Copy the contents of the `__TEMP_DIR__/rhpam-7.0-controller-ee7/SecurityPolicy/` directory to `__EAP_HOME__/bin`. When asked to overwrite files, select *Yes*.
. In the `__EAP_HOME__/standalone/deployments/` directory, create an empty file named `controller.war.dodeploy`. This file ensures that the headless Process Automation Manager controller is automatically deployed when the server starts.

. Complete the following tasks on the system running the headless Process Automation Manager controller:
.. Specify the path to NFS storage in the `org.kie.server.controller.templatefile` system property:
+
[source]
----
<property name="org.kie.server.controller.templatefile" value="<ABSOLUTE_PATH_TO_NFS_STORAGE"/>
----

.. Enable the {KIE_SERVER} watcher service system property:
+
[source]
----
<property name="org.kie.server.controller.templatefile.watcher.enabled" value="<true"/>

----
