[id='clustering-download-eap-bc-proc']
= Downloading and extracting {EAP} 7.1 and {PRODUCT} 

Complete the steps in this section to download and install {EAP} 7.1 and download and repackage {PRODUCT} {PRODUCT_VERSION} for installation in a clustered environment.

.Procedure
. Install {EAP} 7.1 on each node of the cluster:
.. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options:
* *Product: Enterprise Application Platform*
* *Version: 7.1*
.. Click *Download* next to *Red Hat JBoss Enterprise Application Platform 7.1.0*. (`JBEAP-7.1.0/jboss-eap-7.1.0.zip`).
.. Extract the `jboss-eap-7.1.0.zip` file. In the following steps, `_EAP_HOME_` is the `jboss-eap-7.1/jboss-eap-7.1` directory.
. On the cluster node where the {EAP} domain controller will be started, navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal, and select the product and version from the drop-down options:
* *Product: {PRODUCT}*
* *Version: {PRODUCT_VERSION}*
* *Download  {PRODUCT} 7.0.0 {CENTRAL} Deployable for {EAP} 7* (`rhpam-7.0.0.GA-{URL_COMPONENT_CENTRAL}-eap7-deployable.zip`).
. Extract the 
ifdef::DM[]
`rhdm-7.0.0.GA-{URL_COMPONENT_CENTRAL}-eap7-deployable.zip`
endif::[]  
ifdef::PAM[]
`rhpam-7.0.0.GA-{URL_COMPONENT_CENTRAL}-eap7-deployable.zip`
endif::[] 
file to a temporary directory. In the following examples this directory is called `__TEMP_DIR__`.

. Repackage the `business-central.war` file:
.. Navigate to the `TEMP_DIR_/rhpam-7.0.1.GA-{URL_COMPONENT_CENTRAL}-eap7-deployable/jboss-eap-7.1` directory.
.. Select the contents of the  `_TEMP_DIR_/rhpam-7.0.1.GA-{URL_COMPONENT_CENTRAL}-eap7-deployable/jboss-eap-7.1` directory and create the `business-central.zip` file.
..  Rename `business-central.zip` file to `business-central.war`. This is the file that you will use to deploy {CENTRAL} on the cluster nodes.
.. If desired, copy the new `business-central.war` file to a location that is more convenient to deploy from.
