[id='clustering-headless-controller-proc']
= Clustering with the headless Process Automation Manager controller

You can configure {KIE_SERVER} to run in managed or unmanaged mode. If {KIE_SERVER} is unmanaged, you must manually create and maintain containers. If {KIE_SERVER} is managed, the Process Automation Manager controller manages the {KIE_SERVER} configuration and you interact with the controller to create and maintain containers.

The Process Automation Manager controller is integrated with {CENTRAL}. However, if you do not install {CENTRAL}, you can install the headless Process Automation Manager controller and use the REST API or the {KIE_SERVER} Java Client API to interact with it.

.Prerequisites
* A backed-up {EAP} installation version 7.1 or higher is available. The base directory of the {EAP} installation is referred to as `__EAP_HOME__`. 
* Sufficient user permissions to complete the installation are granted.
* An NFS server with a mounted partition is available.

.Procedure
. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options:

* Product: {PRODUCT}
* Version: {PRODUCT_VERSION}
. Download *{PRODUCT} {PRODUCT_VERSION_LONG} Add Ons* (the `{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-add-ons.zip` file).
. Unzip the `{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-add-ons.zip` file. The `{PRODUCT_INIT}-{PRODUCT_VERSION}-controller-ee7.zip` file is in the unzipped directory.
. Extract the `{PRODUCT_INIT}-{PRODUCT_VERSION}-controller-ee7.zip` file to a temporary directory. In the following examples this directory is called `__TEMP_DIR__`.

. Repackage the `controller.war` directory:
.. Navigate to the `TEMP_DIR_/{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-add-ons/{PRODUCT_INIT}-{PRODUCT_VERSION}-controller-ee7/controller.war` directory.
.. Select the contents of the  `_TEMP_DIR_/{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-add-ons/{PRODUCT_INIT}-{PRODUCT_VERSION}-controller-ee7/controller.war` directory and create the `controller.zip` file.
..  Rename `controller.zip` to `controller.war`. This is the file that you will use to deploy the controller on the cluster nodes.
.. If desired, copy the new `controller.war` file to a location that is more convenient to deploy from.

. If you want to use a security manager with the controller, copy the contents of the  `__TEMP_DIR__/{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-add-ons/{PRODUCT_INIT}-{PRODUCT_VERSION}-controller-ee7/SecurityPolicy`
directory to the `_EAP_HOME_/bin` directory on each node of the cluster.
. Add {EAP} management users to the main node of the cluster (where you configured the `domain.xml` file) as described in the https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.1/html-single/configuration_guide/[_{EAP} 7.1 Configuration Guide_].
. On each node of the cluster, add {KIE_SERVER} administration users as described in {URL_INSTALLING_ON_EAP}[_{INSTALLING_ON_EAP}_].
. On each node of the cluster, edit the `_EAP_HOME_/domain/configuration/host.xml` file:
.. Enable the {KIE_SERVER} watcher service system property:
+
[source]
----
org.kie.server.controller.templatefile.watcher.enabled=true
----
.. In the `org.kie.server.controller.templatefile` property, specify the absolute path to the NFS storage where the memory configuration is stored:
+
[source]
----
org.kie.server.controller.templatefile=<absolute_path_to_NFS_storage>
----

. To deploy the `controller.war` file that you created previously into the server group, complete the following steps:
.. Log in to the {EAP} `Administration` console of your domain as a `management` user.
.. Click *Deployments -> Server Groups-> main-server-group* and click *Add*.
.. In the dialog box, click *Upload a new deployment* and click *Next*.
.. In the *Upload Deployments* dialog box, click *Browse*, select the `controller.war` file, and click *Next*.
.. Click *Enable* and  click *Next*.
+
[NOTE]
====
It is important to check deployment unit readiness with every cluster member.

When a deployment unit is created on a cluster node, it takes some time before it is distributed among all cluster members. You can check the deployment status using the server Administration console or REST API. However, if the query is sent to the node where the deployment was originally issued, the query will return a value of `deployed`. If the query is sent to a node where the deployment has not yet been distributed, the query returns `DeploymentNotFoundException`.
====

For more information about installing {CENTRAL}, see  {URL_INSTALLING_ON_EAP}[_{INSTALLING_ON_EAP}_].


