[id='clustering-smartrouter-install-proc']
= Clustering Smart Router for a runtime environment

Smart Router enables you to aggregate multiple independent {KIE_SERVER} instances as though they are a single server. It performs the role of an intelligent load balancer because it can both route requests to individual {KIE_SERVERS} and aggregate data from different {KIE_SERVERS}. Through aliases, Smart Router is a proxy to {KIE_SERVERS}. Smart Router performs the following tasks:

* Collects information from various server instances in a single client request
* Finds the right server for a specific request
* Aggregates responses from different servers
* Provides efficient load-balancing
* Manages changing environments, for example adding and removing server instances
* Manages registration with the {KIE_SERVER} controller

This section describes how to install Smart Router and configure


.Prerequisites
* {KIE_SERVER} is installed on each node of a {EAP} 7.1 cluster.

.Procedure
. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options:
* *Product:* {PRODUCT_SHORT}
* *Version:* {PRODUCT_VERSION}
. Download *{PRODUCT} {PRODUCT_VERSION_LONG} Add-Ons*.
. Extract the downloaded `{PRODUCT_FILE}-add-ons.zip` file to a temporary directory. The `rhpam-7.0-smart-router.jar` file is in the exatracted `{PRODUCT_FILE}-add-ons` directory.
. In the `_EAP_HOME_/domain/configuration/domain.xml` file, edit or add the following properties to the `<system-properties>` element:
+ 
[source]
----
<system-properties>
    <property name="org.kie.server.router.host" value="<ROUTER_HOST"/>
    <property name="org.kie.server.router.port" value="<ROUTER_PORT"/>
    <property name="org.kie.server.controller" value="CONTROLLER_URL"/>
    <property name="org.kie.server.controller.token`" value="<CONTROLLER_TOKEN>"/>
    <property name="org.kie.server.controller.user" value="<CONTROLLER_USER"/>
    <property name="org.kie.server.controller.pwd" value="<CONTROLLER_PWD"/>
    <property name="org.kie.server.router.config.watcher.enabled" value="<TRUE"/>
    <property name="org.kie.server.router.repo" value="<<ABSOLUTE_PATH_TO_NFS_STORAGE>"/>
</system-properties>
----
. Start the {KIE_SERVERS} (with the router property): 

+
[options="nowrap"]
----
/standalone.sh --server-config=standalone-full.xml -Djboss.socket.binding.port-offset=100 -Dorg.kie.server.id=hr-server -Dorg.kie.server.location=http://localhost:8180/kie-server/services/rest/server -Dorg.kie.server.router=http://localhost:9000
----

. From the temporary directory, enter the following command to start SmartRouter:
+
[source]
----
java -jar rhpam-7.0-smart-router.jar
----

+
[NOTE]
====
The router is capable of providing an aggregate sort, however the data returned when used through the management console are in raw format. Therefore, sorting is in whatever way  individual servers return. 

Paging is supported in its standard format.
====



