[id='clustering-ks-runtime-standalone-proc']
= Clustering {KIE_SERVER} for a runtime environment
In a runtime environment, {KIE_SERVER} runs rules and processes that support business decisions. The primary benefit of clustering a {KIE_SERVER} runtime environment is load balancing. If activity on one node of the cluster increases, that activity can be shared among the other nodes of the cluster to improve performance.

.Prerequisites
* A {EAP} 7.1 cluster is available. 
* An NFS server with a mounted partition accessible to a {EAP} user is available.

.Procedure
. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options:
* *Product: {PRODUCT}*
* *Version: {PRODUCT_VERSION}*
* Download  *{PRODUCT} 7.0.0 {KIE_SERVER} for All Supported EE7 Containers*
ifdef::PAM[]
(`rhpam-7.0.0.GA-kie-server-ee7.zip`).
endif::PAM[]
ifdef::DM[]
(`rhdm-7.0.0.GA-kie-server-ee7.zip`).
endif::DM[]
ifdef::PAM[]
+
COMMENT: Are these steps relevant?
. Extract the 
ifdef::PAM[]
`rhpam-7.0.0.GA-kie-server-ee7.zip`
endif::PAM[]
ifdef::DM[]
`rhdm-7.0.0.GA-kie-server-ee7.zip`
endif::DM[]
 archive to a temporary directory. In the following examples this directory is called `__TEMP_DIR__`.
. On each node of the cluster, copy the
ifdef::PAM[]
`__TEMP_DIR__/rhpam-7.0.0.GA-kie-server-ee7/rhpam-7.0.0.GA-kie-server-ee7/kie-server.war`
endif::PAM[]
ifdef::DM[]
`__TEMP_DIR__/rhdm-7.0.0.GA-kie-server-ee7/rhdm-7.0.0.GA-kie-server-ee7/kie-server.war`
endif::DM[]
 directory to `__EAP_HOME__/standalone/deployments/`.
+
WARNING: Ensure the names of the {PRODUCT} deployments you are copying do not conflict with your existing deployments in the {EAP} instance.
. Copy the contents of the
ifdef::PAM[]
`__TEMP_DIR__/rhpam-7.0.0.GA-kie-server-ee7/rhpam-7.0.0.GA-kie-server-ee7/SecurityPolicy/`
endif::PAM[]
ifdef::DM[]
`__TEMP_DIR__/rhdm-7.0.0.GA-kie-server-ee7/rhdm-7.0.0.GA-kie-server-ee7/SecurityPolicy/`
endif::DM[]
 to `__EAP_HOME__/bin`. When asked to overwrite files, select *Yes*.
. In the `__EAP_HOME__/standalone/deployments/` directory, create an empty file named `kie-server.war.dodeploy`. This file ensures that {KIE_SERVER} is automatically deployed when the server starts.

. Install the JDBC driver. 
. Edit the `_EAP_HOME_/_MODE_/configuration/domain.xml` file.
.. Add the {KIE_SERVER} and EJB timer data sources to the `full` profile. In these examples,  `ServerName` is the host name of the database:
ifdef::PAM[]
* Add the data source to allow {KIE_SERVER} to connect to the database, for example:
+
[source,xml]
----
<xa-datasource jndi-name="java:/jboss/datasources/rhpam" pool-name="rhpam-RHPAM" use-java-context="true" enabled="true"> 
  <xa-datasource-property name="PortNumber">5432</xa-datasource-property> 
  <xa-datasource-property name="ServerName">myapp-postgresql</xa-datasource-property> 
  <driver>postgresql</driver> 
  <transaction-isolation>TRANSACTION_READ_COMMITTED</transaction-isolation> 
  <security>
    <user-name>rhpam</user-name> 
    <password>BBfPPb2!</password> 
</security> 
</xa-datasource>
----
* Add the data source to enable the EJB timer, for example:
+
[source,xml]
----
<xa-datasource jndi-name="java:jboss/datasources/ejb_timer" pool-name="ejb_timer-EJB_TIMER" use-java-context="true" enabled="true">
    <xa-datasource-property name="DatabaseName">rhpam7</xa-datasource-property> 
    <xa-datasource-property name="PortNumber">5432</xa-datasource-property> 
    <xa-datasource-property name="ServerName">myapp-postgresql</xa-datasource-property> 
    <driver>postgresql</driver> 
    <transaction-isolation>TRANSACTION_READ_COMMITTED</transaction-isolation> 
    <xa-pool> 
        <min-pool-size>10</min-pool-size> 
        <max-pool-size>10</max-pool-size> 
    </xa-pool> 
    <security> 
        <user-name>rhpam</user-name> 
        <password>BBfPPb2!</password> 
    </security> 
</xa-datasource>
----
.. Edit the `data-stores` property. The `datasource-jndi-name` is the JNDI name of the database specified in the previous step. You can enter any name for the value of the `partition` property:
+
[source,xml]
----
<data-stores>      
    <database-data-store name="ejb_timer-EJB_TIMER_ds" datasource-jndi-name="java:jboss/datasources/ejb_timer" database="postgresql" partition="ejb_timer-EJB_TIMER_part" refresh-interval="30000"/>       
</data-stores> 
----
endif::PAM[]
.. Set the value of the `org.jbpm.ejb.timer.tx` system property to `true`.
. Add management users as described in the https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.1/html-single/configuration_guide/[_{EAP} 7.1 Configuration Guide_] and application users as described in {URL_INSTALLING_ON_EAP}[_{INSTALLING_ON_EAP}_].

. Open the `_EAP_HOME_/standalone/configuration/standalone.xml` file and add the following properties to the `<system-properties>` tag:

* `org.kie.server.persistence.ds`: The JNDI name of your data source
* `org.kie.server.persistence.dialect`: The hibernate dialect for your database
. If your environment is connected to Smart Router, on the java process running Smart Router do the following:
.. Define the data source driver.
+
.PostgreSQL Driver Definition
====
[source,xml]
----
<driver name="postgres" module="org.postgresql">
  <xa-datasource-class>org.postgresql.xa.PGXADataSource</xa-datasource-class>
</driver>
----
====
+
Ensure that the data sources contain schemas. If your data source does not contain schemas, ensure your nodes start one at a time.

.. Enable the {KIE_SERVER} watcher service system property:
+
[source]
----
org.kie.server.router.config.watcher.enabled=true
----
.. In the `org.kie.server.router.repo` property, specify the absolute path to the NFS storage where the memory configuration is stored:
+
[source]
----
org.kie.server.router.repo=<absolute_path_to_NFS_storage>
----

. If your environment is managed by the headless {PRODUCT} controller, on the java process running the headless {PRODUCT} controller, do the following:

.. Enable the {KIE_SERVER} watcher service system property:
+
[source]
----
org.kie.server.controller.templatefile.watcher.enabled=true
----
.. In the `org.kie.server.controller.templatefile` property, specify the absolute path to the NFS storage where the memory configuration is stored:
+
[source]
----
org.kie.server.controller.templatefile=<absolute_path_to_NFS_storage>
----
