[id='clustering-smartrouter-install-proc']
= Clustering {KIE_SERVER} for a runtime environment

The {KIE_SERVER} router allows you to aggregate multiple independent KIE server instances as though they are a single server. Use the following procedure to start the {KIE_SERVER} router.


This example uses the following default system properties:

* `org.kie.server.router.host=localhost`
* `org.kie.server.router.port=9000`
* `org.kie.server.controller.user=kieserver`
* `org.kie.server.controller.pwd=kieserver1!`


.Procedure
. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options:
* *Product:* {PRODUCT_SHORT}
* *Version:* {PRODUCT_VERSION}
. Download *{PRODUCT} {PRODUCT_VERSION_LONG} Add-Ons*.
. Extract the downloaded `{PRODUCT_FILE}-add-ons.zip` file to a temporary directory.

. Start the router (without the controller property): 
+
[options="nowrap"]
----
java -jar target/kie-server-router-proxy-7.0.0-SNAPSHOT.jar
----
+ 
The host name and port of the router can be changed using system properties:

* `org.kie.server.router.host`
* `org.kie.server.router.port`

. Start the KIE servers (with the router property): 
+
[options="nowrap"]
----
/standalone.sh --server-config=standalone-full.xml -Djboss.socket.binding.port-offset=100 -Dorg.kie.server.id=hr-server -Dorg.kie.server.location=http://localhost:8180/kie-server/services/rest/server -Dorg.kie.server.router=http://localhost:9000
----

. Restart the router with the controller property:
+
[options="nowrap"]
----
java -Dorg.kie.server.controller=http://localhost:8080/kie-wb/rest/controller -jar target/kie-server-router-proxy-7.0.0-SNAPSHOT.jar
----
+ 
The following system properties can also be used for communicating between the router and controller:

* `org.kie.server.controller`
* `org.kie.server.controller.user`
* `org.kie.server.controller.pwd`
* `org.kie.server.controller.token`


[NOTE]
====
The router is capable of providing an aggregate sort, however the data returned when used through the management console are in raw format. Therefore, sorting is in whatever way  individual servers return. 

Paging is supported in its standard format.
====


If your environment is connected to Smart Router, on the java process running Smart Router do the following:


.. Enable the {KIE_SERVER} watcher service system property:
+
[source]
----
org.kie.server.controller.templatefile.watcher.enabled=true
----
.. In the `org.kie.server.controller.templatefile` property, specify the absolute path to the NFS storage where the memory configuration is stored:
+
[source]
----
org.kie.server.controller.templatefile=<absolute_path_to_NFS_storage>
----

