[id='clustering-dm-install-proc_{context}']
= Installing and configuring {CENTRAL} on cluster nodes

A Java messaging server (JMS) broker resource adapter enables your applications to communicate with any messaging provider. It specifies how components such as message-driven beans, Enterprise JavaBeans, and servlets can send or receive messages. {EAP} 7 includes an integrated Artemis resource adapter.

Complete the steps in this section to install and configure {CENTRAL} with the {EAP} integrated JMS resource adapter.

.Prerequisites
* A Red Hat JBoss EAP 7.1 cluster with Java Messaging Server high availability configured is available.
* Elasticsearch is installed and running on one node of the cluster.

.Procedure
. In the `_EAP_HOME_/domain/configuration/domain.xml` file, make the following changes in each `server-group`:
.. To enable high availability, change the `profile` to `"full-ha"` and the `socket-binding-group` to `"full-ha-sockets"`.
.. To prevent {CENTRAL} from running out of memory, increase the JVM maximum heap size to `1500m`,
+
[source]
----
<server-group name="some-server-group" profile="full-ha">
    <jvm name="default">
        <heap size="1000m" max-size="1500m"/>
    </jvm>
    <socket-binding-group ref="full-ha-sockets"/>
</server-group>
----
. On the cluster node where the domain controller will be started, navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options:
* *Product: {PRODUCT}*
* *Version: {PRODUCT_VERSION}*
* *Download  {PRODUCT} 7.0.0 {CENTRAL} Deployable for {EAP} 7* (`rhpam-7.0.0.GA-{URL_COMPONENT_CENTRAL}-eap7-deployable.zip`).
. Extract the 
ifdef::DM[]
`rhdm-7.0.0.GA-{URL_COMPONENT_CENTRAL}-eap7-deployable.zip`
endif::[]  
ifdef::PAM[]
`rhpam-7.0.0.GA-{URL_COMPONENT_CENTRAL}-eap7-deployable.zip`
endif::[] 
file to a temporary directory. In the following examples this directory is called `__TEMP_DIR__`.
. Copy the contents of the 
ifdef::DM[]
`__TEMP_DIR__/rhdm-7.0.0.GA-{URL_COMPONENT_CENTRAL}-eap7-deployable/jboss-eap-7.1`
endif::[]  
ifdef::PAM[]
`__TEMP_DIR__/rhpam-7.0.0.GA-{URL_COMPONENT_CENTRAL}-eap7-deployable/jboss-eap-7.1`
endif::[]
directory to `__EAP_HOME__`. When asked to overwrite files or merge directories, select *Yes*.
+
WARNING: Ensure the names of the {PRODUCT} deployments you are copying do not conflict with your existing deployments in the {EAP} instance.
. Navigate to the `_EAP_HOME_/standalone/deployments/business-central.war` directory.
. Package the contents of the  `_EAP_HOME_/standalone/deployments/business-central.war` directory into a new `business-central.war` file that you will use to deploy {CENTRAL} on the cluster nodes.
. If desired, copy the new `business-central.war` file to a different location that is more convenient to deploy from.
. Edit the following properties in the `_EAP_HOME_/domain/configuration/domain.xml` file, where:
* `<NIOGIT_DIR>` is the location of Git repositories stored under ``.niogit`, on an NFS mounted partition.
* `<ELASTICSEARCH_NODE_IP>` and `<AMQ_NODE_IP>` are IP addresses where Elasticseach and AMQ Broker are installed.
* `<JMS_USER>` is an {EAP} application user. It is the user used by {CENTRAL} to connect to the  embedded JMS broker. Should be the same user as defined in cluster user. Role must be defined in security settings.
* `<JMS_USER_PASSWORD>` is the password for `<JMS_USER>`.
+
[source,xml]
----
<system-properties>
  <property name="org.uberfire.nio.git.dir" value="
      <NIOGIT_DIR>"/> 
  <property name="appformer-jms-connection-mode" value="REMOTE"/>
  <property name="appformer-jms-url" value="tcp://<AMQ_NODE_IP>:61616"/>
  <property name="appformer-jms-username" value="<JMS_USER>  "/>
  <property name="appformer-jms-password" value="<JMS_USER_PASSWORD>"/>
  <property name="org.appformer.ext.metadata.index" value="elastic"/>
  <property name="org.appformer.ext.metadata.elastic.port" value="9300"/>
  <property name="org.appformer.ext.metadata.elastic.host" 
      value="<ELASTICSEARCH_NODE_IP>"/>
  <property name="org.appformer.ext.metadata.elastic.cluster" 
      value="kie-cluster"/>
  <property name="org.appformer.ext.metadata.elastic.retries" value="10"/>
</system-properties>
----
. To configure the embedded JMS broker, edit the `domain.xml` file as follows:

.. To create an `outbound-socket-binding` pointing to the remote messaging server, in the `domain.xml` file add the following lines to the `<socket-binding-group name="full-sockets"` tag, where `localhost` is the host name or IP address of the remote {EAP} instance:
+
[source]
----
 <socket-binding-group name="full-sockets" default-interface="public">
.
.
.
    <outbound-socket-binding name="remote-server">
      <remote-destination host="localhost" port="8080"/>
    </outbound-socket-binding>
----
.. To create a `remote-connector` referencing the `outbound-socket-binding`, locate the `<subsystem xmlns="urn:jboss:domain:messaging-activemq:2.0">` profile and add the following lines to the `"<server name="default">` section:
+
[source]
----
<http-connector name="remote-http-connector" socket-binding="remote-server" endpoint="http-acceptor"/>
----
.. To create a `connection-factory` referencing the new `remote-connector` add the following line to the `"<server name="default">` section:
+
[source]
----
<connection-factory name="remote-artemis" entries="java:/jms/remoteCF" connectors="remote-http-connector"/>
----
.. Delete `<property name="appformer-jms-url" value="tcp://<AMQ_NODE_IP>:61616"/>`.
.. Change the value of the `appformer-jms-connection-mode` property to `"JNDI"`.
.. Add the following property:
+
[source]
----
<property name="appformer-jms-connection-factory" value="java:/jms/remoteCF"/>
----
. Edit the `server-groups` element to specify the server groups to be used in the cluster and their JVM parameters.
. Edit the `host.xml` file to specify the servers to be created on that node. 
. Configure individual server nodes in the `main-server-group` element in the `_EAP_HOME_/domain/configuration/host.xml` file with properties defined in
ifdef::PAM[]
<<_cluster_properties_pam>>.
endif::PAM[]
ifdef::DM[]
<<_cluster_properties_BRMS>>.
endif::DM[]
+
ifdef::PAM[]
[id='_cluster_properties_pam']
.Cluster Node Properties
[cols="1,1,2", frame="all", options="header"]
|===
|Property Name
|Value
|Description

|jboss.node.name
|nodeOne
|Node name unique within the cluster.

|org.uberfire.metadata.index.dir
|/home/jbpm/node[N]/index
|Location where the index for search is to be created (maintained by Apache Lucene).

|org.uberfire.nio.git.daemon.host
|nodeOne
|The name of the daemon host machine in a physical cluster.

|org.uberfire.nio.git.daemon.port
|9418
|Port used by the VFS repo to accept client connections. The port must be unique for each cluster member.

|org.uberfire.nio.git.dir
|/home/jbpm/node[N]/repo
|Git (VFS) repository location on node[N].

|org.uberfire.nio.git.ssh.host
|nodeOne
|The name of the SSH host machine in a physical cluster.

|org.uberfire.nio.git.ssh.port
|8003
|The unique port number for ssh access to the GIT repo for a cluster running on physical machines.

|org.uberfire.nio.git.ssh.hostport and org.uberfire.nio.git.daemon.hostport
|8003 and 9418
|In a virtualized environment, the outside port to be used.

|appformer-jms-connection-factory
|java:/ConnectionFactory
|The Java messaging service connection factory of the {EAP} installation.

|org.appformer.ext.metadata.index
|elastic
|

|org.appformer.ext.metadata.elastic.cluster
|`kie-cluster`
|The name of the Elasticsearch cluster

|org.appformer.ext.metadata.elastic.port
|9300
|The Elasticsearch port

|org.appformer.ext.metadata.elastic.host
|Elasticsearch node IP address
|

|org.appformer.ext.metadata.elastic.retries
|10
|The number of times Elasticsearch retries...
|===
endif::PAM[]
ifdef::DM[]
+
[id='_cluster_properties_BRMS']
.Cluster Node Properties
[cols="1,1,2", frame="all", options="header"]
|===
|Property Name
|Value
|Description

|org.uberfire.nio.git.dir
|/home/jbrm/node[N]/repo
|Git (VFS) repository location on node[N].

|jboss.node.name
|nodeOne
|Node name unique within the cluster.

|org.uberfire.nio.git.daemon.port
|9418
|Port used by the VFS repo to accept client connections. The port must be unique for each cluster member.

|org.uberfire.metadata.index.dir
|/home/jbrm/node[N]/index
|Location where the index for search is to be created (maintained by Apache Lucene).

|org.uberfire.nio.git.ssh.port
|8003
|The unique port number for ssh access to the Git repo for a cluster running on physical machines.

|org.uberfire.nio.git.daemon.host
|nodeOne
|The name of the daemon host machine in a physical cluster.

|org.uberfire.nio.git.ssh.host
|nodeOne
|The name of the SSH host machine in a physical cluster.
|===
endif::DM[]
+
ifdef::PAM[]

.Cluster nodeOne Configuration
====
[source,xml]
----
<system-properties>
 <property name="org.uberfire.nio.git.dir" value="/tmp/rhpam/nodeone"
           boot-time="false"/>
 <property name="jboss.node.name" value="nodeOne" boot-time="false"/>
 <property name="org.uberfire.cluster.id" value="rhpam-cluster" boot-time="false"/>
 <property name="org.uberfire.cluster.local.id" value="nodeOne_12345"
           boot-time="false"/>
 <property name="org.uberfire.cluster.vfs.lock" value="vfs-repo" boot-time="false"/>
 <property name="org.uberfire.nio.git.daemon.host" value="nodeOne"/>
 <property name="org.uberfire.nio.git.daemon.port" value="9418" boot-time="false"/>
 <property name="org.uberfire.nio.git.daemon.hostport" value="9418"
           boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.port" value="8003" boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.hostport" value="8003" boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.host" value="nodeOne"/>
 <property name="org.uberfire.metadata.index.dir" value="/tmp/jbpm/nodeone"
           boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.cert.dir" value="/tmp/jbpm/nodeone"
           boot-time="false"/>
</system-properties>
----
====
endif::PAM[]
+
ifdef::PAM[]

.Cluster nodeTwo Configuration
====
[source,xml]
----
<system-properties>
 <property name="org.uberfire.nio.git.dir" value="/tmp/rhpam/nodetwo"
           boot-time="false"/>
 <property name="jboss.node.name" value="nodeTwo" boot-time="false"/>
 <property name="org.uberfire.cluster.id" value="rhpam-cluster" boot-time="false"/>
 <property name="org.uberfire.cluster.local.id" value="nodeTwo_12346"
           boot-time="false"/>
 <property name="org.uberfire.cluster.vfs.lock" value="vfs-repo" boot-time="false"/>
 <property name="org.uberfire.nio.git.daemon.host" value="nodeTwo" />
 <property name="org.uberfire.nio.git.daemon.port" value="9419" boot-time="false"/>
 <property name="org.uberfire.nio.git.daemon.hostport" value="9419"
           boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.port" value="8004" boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.hostport" value="8004" boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.host" value="nodeTwo" />
 <property name="org.uberfire.metadata.index.dir" value="/tmp/jbpm/nodetwo"
           boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.cert.dir" value="/tmp/jbpm/nodetwo"
           boot-time="false"/>
</system-properties>
----
====
endif::PAM[]
+
ifdef::PAM[]

.Cluster nodeThree Configuration
====
[source,xml]
----
<system-properties>
 <property name="org.uberfire.nio.git.dir" value="/tmp/rhpam/nodethree"
           boot-time="false"/>
 <property name="jboss.node.name" value="nodeThree" boot-time="false"/>
 <property name="org.uberfire.cluster.id" value="rhpam-cluster" boot-time="false"/>
 <property name="org.uberfire.cluster.local.id" value="nodeThree_12347"
           boot-time="false"/>
 <property name="org.uberfire.cluster.vfs.lock" value="vfs-repo" boot-time="false"/>
 <property name="org.uberfire.nio.git.daemon.host" value="nodeThree" />
 <property name="org.uberfire.nio.git.daemon.port" value="9420" boot-time="false"/>
 <property name="org.uberfire.nio.git.daemon.hostport" value="9420"
           boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.port" value="8005" boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.hostport" value="8005" boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.host" value="nodeThree" />
 <property name="org.uberfire.metadata.index.dir" value="/tmp/jbpm/nodethree"
           boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.cert.dir" value="/tmp/jbpm/nodethree"
           boot-time="false"/>
</system-properties>
----
====
endif::PAM[]
ifdef::DM[]

.Cluster nodeOne Configuration
====
[source,xml]
----
<system-properties>
 <property name="org.uberfire.nio.git.dir" value="/tmp/brms/nodeone"
           boot-time="false"/>
 <property name="jboss.node.name" value="nodeOne" boot-time="false"/>
 <property name="org.uberfire.cluster.id" value="brms-cluster" boot-time="false"/>
 <property name="org.uberfire.cluster.local.id" value="nodeOne_12345"
           boot-time="false"/>
 <property name="org.uberfire.cluster.vfs.lock" value="vfs-repo" boot-time="false"/>
 <property name="org.uberfire.nio.git.daemon.port" value="9418" boot-time="false"/>
 <property name="org.uberfire.metadata.index.dir" value="/tmp/jbrm/nodeone"
           boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.cert.dir" value="/tmp/jbpm/nodeone"
           boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.port" value="8003" boot-time="false"/>
 <property name="org.uberfire.nio.git.daemon.host" value="nodeOne" />
 <property name="org.uberfire.nio.git.ssh.host" value="nodeOne" />
 <property name="org.uberfire.nio.git.ssh.hostport" value="8003" boot-time="false"/>
 <property name="org.uberfire.nio.git.daemon.hostport" value="9418"
           boot-time="false"/>
</system-properties>
----
====
endif::DM[]
+
ifdef::DM[]

.Cluster nodeTwo Configuration
====
[source,xml]
----
<system-properties>
 <property name="org.uberfire.nio.git.dir" value="/tmp/brms/nodetwo"
           boot-time="false"/>
 <property name="jboss.node.name" value="nodeTwo" boot-time="false"/>
 <property name="org.uberfire.cluster.id" value="brms-cluster" boot-time="false"/>
 <property name="org.uberfire.cluster.local.id" value="nodeTwo_12346"
           boot-time="false"/>
 <property name="org.uberfire.cluster.vfs.lock" value="vfs-repo" boot-time="false"/>
 <property name="org.uberfire.nio.git.daemon.port" value="9418" boot-time="false"/>
 <property name="org.uberfire.metadata.index.dir" value="/tmp/jbrm/nodetwo"
           boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.cert.dir" value="/tmp/jbpm/nodetwo"
           boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.port" value="8003" boot-time="false"/>
 <property name="org.uberfire.nio.git.daemon.host" value="nodeTwo" />
 <property name="org.uberfire.nio.git.ssh.host" value="nodeTwo" />
 <property name="org.uberfire.nio.git.ssh.hostport" value="8003" boot-time="false"/>
 <property name="org.uberfire.nio.git.daemon.hostport" value="9418"
           boot-time="false"/>
</system-properties>
----
====
endif::DM[]
+
ifdef::DM[]

.Cluster nodeThree Configuration
====
[source,xml]
----
<system-properties>
 <property name="org.uberfire.nio.git.dir" value="/tmp/brms/nodethree"
           boot-time="false"/>
 <property name="jboss.node.name" value="nodeThree" boot-time="false"/>
 <property name="org.uberfire.cluster.id" value="brms-cluster" boot-time="false"/>
 <property name="org.uberfire.cluster.local.id" value="nodeThree_12347"
           boot-time="false"/>
 <property name="org.uberfire.cluster.vfs.lock" value="vfs-repo" boot-time="false"/>
 <property name="org.uberfire.nio.git.daemon.port" value="9418" boot-time="false"/>
 <property name="org.uberfire.metadata.index.dir" value="/tmp/jbrm/nodethree"
           boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.cert.dir" value="/tmp/jbpm/nodethree"
           boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.port" value="8003" boot-time="false"/>
 <property name="org.uberfire.nio.git.daemon.host" value="nodeThree" />
 <property name="org.uberfire.nio.git.ssh.host" value="nodeThree" />
 <property name="org.uberfire.nio.git.ssh.hostport" value="8003" boot-time="false"/>
 <property name="org.uberfire.nio.git.daemon.hostport" value="9418"
           boot-time="false"/>
</system-properties>
----
====
endif::DM[]
. Add management users as described in the https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.1/html-single/configuration_guide/[_{EAP} 7.1 Configuration Guide_] and application users as described in {URL_INSTALLING_ON_EAP}[_{INSTALLING_ON_EAP}_].
. Start the domain and host controllers:
+
* On Linux or UNIX-based systems, enter:
+
`_EAP_HOME_/bin/domain.sh`
+
On Windows, enter:
+
`_EAP_HOME_/bin/domain.bat`
+
For more information, see the following sections of the _Red Hat JBoss EAP 7.1 Configuration Guide_:
* https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.0/html/configuration_guide/starting_and_stopping_jboss_eap#starting_jboss_eap["Starting JBoss EAP"]
* https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.0/html/configuration_guide/jboss_eap_management#managed_domain_configuration_files["Managed Domain Configuration Files"]
. Review the `_EAP_HOME_/domain/servers/SERVER_NAME/log/server.log` file to verify that the nodes are available.
. To deploy the `business-central.war` file that you created previously into the server group, complete the following steps:
.. Log in to the {EAP} `Administration` console of your domain as a `management` user.
.. Click *Deployments -> Server Groups-> *main-server-group* and click *Add*.
.. In the dialog box, click *Upload a new deployment* and click *Next*.
.. In the *Upload Deployments* dialog box, click *Browse*, select the `business-central.war` file, and click *Next*.
.. Click *Enable* then click *Next*.
+
[NOTE]
====
It is important to check deployment unit readiness with every cluster member.

When a deployment unit is created on a cluster node, it takes some time before it is distributed among all cluster members. You can check the deployment status using the server Administration console or REST API. However, if the query is sent to the node where the deployment was originally issued, the query will return a value of `deployed`. If the query is sent to a node where the deployment has not yet been distributed, the query returns `DeploymentNotFoundException`.
====

For more information about installing {CENTRAL}, see  {URL_INSTALLING_ON_EAP}[_{INSTALLING_ON_EAP}_].

