[id='clustering-dm-install-proc_{context}']
= Installing and configuring {CENTRAL} on cluster nodes

A Java messaging server (JMS) broker resource adapter enables your applications to communicate with any messaging provider. It specifies how components such as message-driven beans, Enterprise JavaBeans, and servlets can send or receive messages. {EAP} 7 includes an integrated Artemis resource adapter.

Complete the steps in this section to install and configure {CENTRAL} with the {EAP} integrated JMS resource adapter.

.Prerequisites
* A Red Hat JBoss EAP 7.1 cluster is available.
* Elasticsearch is installed and running on one node of the cluster.

.Procedure
. Navigate to the `_EAP_HOME_/standalone/deployments/business-central.war` directory.
. Select the contents of the  `_EAP_HOME_/standalone/deployments/business-central.war` directory and create the `business-central.zip` file.
.  Rename `business-central.zip` file to `business-central.war`. This is the file that you will use to deploy {CENTRAL} on the cluster nodes.
. If desired, copy the new `business-central.war` file to a location that is more convenient to deploy from.

. Add {EAP} management users as described in the https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.1/html-single/configuration_guide/[_{EAP} 7.1 Configuration Guide_] and {CENTRAL} adminstration users as described in {URL_INSTALLING_ON_EAP}[_{INSTALLING_ON_EAP}_].
. Start the domain and host controllers:
+
* On Linux or UNIX-based systems, enter:
+
`_EAP_HOME_/bin/domain.sh`
+
On Windows, enter:
+
`_EAP_HOME_/bin/domain.bat`
+
For more information, see the following sections of the _Red Hat JBoss EAP 7.1 Configuration Guide_:
* https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.0/html/configuration_guide/starting_and_stopping_jboss_eap#starting_jboss_eap["Starting JBoss EAP"]
* https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.0/html/configuration_guide/jboss_eap_management#managed_domain_configuration_files["Managed Domain Configuration Files"]
. Review the `_EAP_HOME_/domain/servers/SERVER_NAME/log/server.log` file to verify that the nodes are available.
. To deploy the `business-central.war` file that you created previously into the server group, complete the following steps:
.. Log in to the {EAP} `Administration` console of your domain as a `management` user.
.. Click *Deployments -> Server Groups-> main-server-group* and click *Add*.
.. In the dialog box, click *Upload a new deployment* and click *Next*.
.. In the *Upload Deployments* dialog box, click *Browse*, select the `business-central.war` file, and click *Next*.
.. Click *Enable* and  click *Next*.
+
[NOTE]
====
It is important to check deployment unit readiness with every cluster member.

When a deployment unit is created on a cluster node, it takes some time before it is distributed among all cluster members. You can check the deployment status using the server Administration console or REST API. However, if the query is sent to the node where the deployment was originally issued, the query will return a value of `deployed`. If the query is sent to a node where the deployment has not yet been distributed, the query returns `DeploymentNotFoundException`.
====

For more information about installing {CENTRAL}, see  {URL_INSTALLING_ON_EAP}[_{INSTALLING_ON_EAP}_].

