[id='clustering-dev-proc']
= Clustering {PRODUCT} for a development (authoring) environment

Developers use {PRODUCT} to author rules and processes that assist users with decision making. The primary benefit of clustering {PRODUCT} development environments is high availability. If clustering is configured and Developer X is working on Node1 and that node fails, Developer X's work is preserved and visible on any other node of the cluster.

Most development environments consist of {CENTRAL} for creating rules and processes and at least one {KIE_SERVER} to test those rules and processes. 

[NOTE]
====
You can also use this configuration for runtime environments if you want to use {CENTRAL} to manage the {KIE_SERVER}s in the cluster.
====

.Prerequisite
An NFS server with a mounted partition accessible to a {EAP} user is available.

.Procedure
. Install and configure Elasticsearch as described in <<clustering-elasticsearch-proc_{context}>>.
. Install {EAP} and configure as described in <<clustering-create-dev-proc>>.
. Install and configure {CENTRAL} as described in <<clustering-dm-install-proc_{context}>>.