[id='jws-zip-install-proc']

= Installing {KIE_SERVER} on Red Hat JBoss Web Server

{KIE_SERVER} provides the runtime environment for business assets and accesses the data stored in the assets repository (knowledge store). This section provides instructions for installing {KIE_SERVER} on an existing Red Hat JBoss Web Server 3.1 with Tomcat 8 instance.

.Prerequisites
* A backed up Red Hat JBoss Web Server 3.1 with Tomcat 8 or higher server installation. The base directory of the JBoss Web Server installation is referred to as `__JWS_HOME__`. 
* Sufficient user permissions to complete the installation.
* The `rhdm-7.0-kie-server-jws.zip` file. To download this file:

. Click *Download* next to *{PRODUCT} 7.0.0 Add Ons* on the Product Downloads page of the https://access.redhat.com[Red Hat Customer Portal].
. Unzip the `rhdm-7.0.0.GA-add-ons.zip` file. The `rhdm-7.0-kie-server-jws.zip` file is in the unzipped directory.

.Procedure
. Extract the `rhdm-7.0-kie-server-jws.zip` archive to a temporary directory. In the following examples, this directory is called `__TEMP_DIR__`.
. Copy the `__TEMP_DIR__/rhdm-7.0-kie-server-jws/kie-server.war` directory to `__JWS_HOME__/standalone/deployments/`.
+
WARNING: Ensure the names of the {PRODUCT} deployments you are copying do not conflict with your existing deployments in the Red Hat JBoss Web Server instance.
. Copy the contents of the `__TEMP_DIR__/rhdm-7.0-kie-server-jws/SecurityPolicy/` to `__JWS_HOME__/bin`. When asked to overwrite files, select *Yes*.
. In the `__JWS_HOME__/standalone/deployments/` directory, create an empty file named `kie-server.war.dodeploy`. This file ensures that {KIE_SERVER} is automatically deployed when the server starts.

