
[[bxms_rn_tech_preview]]
= Technical Preview

This section lists features that are technical previews in {PRODUCT} {PRODUCT_VERSION} Limited Availability. Where they are listed in the documentation these features also have a note similar to the following:

[IMPORTANT]
====
This feature a Technology Preview feature only. Technology Preview features
are not supported with Red Hat production service level agreements (SLAs), might
not be functionally complete, and Red Hat does not recommend to use them for
production. These features provide early access to upcoming product features,
enabling customers to test functionality and provide feedback during the
development process.
For more information on Red Hat Technology Preview features support scope, 
see https://access.redhat.com/support/offerings/techpreview/
====

* Deployments perspective 
+
This perspective is disabled by default. COMMENT: To enable it.... If you choose to enable the Deployments perspective, be aware that it will only work (provide happy path).
* Fine-grained security configuration 
* Guided Decision Trees
* Guided Score Cards

