
[id='ba-dm-rn-intro-con']

= About {PRODUCT}

ifdef::PAM[]
{PRODUCT} is the Red Hat middleware platform for creating business automation applications and microservices. It enables enterprise business and IT users to document, simulate, manage, automate, and monitor business processes and policies. It is designed to empower business and IT users to collaborate more effectively, so business applications can be changed easily and quickly.

{PRODUCT} combines business rules management, complex event processing, Decision Model & Notation (DMN) execution, and {PLANNER} for solving planning problems. It automates business decisions and makes that logic available to the entire business.

Business assets such as rules, decision tables, and DMN models are stored in a central repository. This ensures consistency, transparency, and the ability to audit across the business. Business users can modify business logic without requiring assistance from IT personnel.

{PRODUCT} is fully supported on OpenShift and can be installed on various platforms.

endif::PAM[]

ifdef::DM[]

{PRODUCT} is an open source decision management platform that combines business rules management, complex event processing, Decision Model & Notation (DMN) execution, and Business Optimizer for solving planning problems. It automates business decisions and makes that logic available to the entire business.

Business assets such as rules, decision tables, and DMN models are stored in a central repository. This ensures consistency, transparency, and the ability to audit across the business. Business users can modify business logic without requiring assistance from IT personnel.

{PRODUCT} is fully supported on OpenShift and can be installed on various platforms.

//The list of supported configurations for {PRODUCT} is available at the https://access.redhat.com/articles/705183[Red Hat Customer Portal]. *<MH>Replace with the correct link and uncomment paragraph. Don and Prakash are to to provide this link, which is part of the https://docs.google.com/document/d/1W5Uyxfohv-C5J8zyjcuN7ogaTsNaP3JCXhHLAN43uIs/edit doc, located in the Supported Configuration page:
//https://access.redhat.com/site/articles/704703
//https://access.redhat.com/site/articles/705183
//row</MH>*
endif::DM[]
