[id='_chap_introduction']
= Introduction
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:sourcedir: .

[id='_about_dm_for_wls']
== About {PRODUCT} for Oracle WebLogic Server

You can install {PRODUCT} {KIE_SERVER} and the {KIE_SERVER} controller on Oracle Weblogic Server. The deployable ZIP file installation consists of two ZIP files, one for {KIE_SERVER} and one for {KIE_SERVER} controller.

This guide explains how to install {KIE_SERVER} on a full profile version of Oracle WebLogic Server.

Before installation, several configuration steps have to be performed to enable a successful setup. This guide will outline these steps.

Before you proceed, make sure you have access to the server on Oracle WebLogic Server and that you are able to successfully access Oracle WebLogic Server's administrative console through a web browser (usually at `http://_TARGET_SERVER_:7001/console`).

{PRODUCT} for Oracle WebLogic Server is distributed as a WAR file. It is then deployed as an exploded archive and configured as any other web application.
