[id='sso-client-adapter-proc']
= Set up the RH-SSO client adapter for {EAP}

To set up the RH-SSO client adapter for {EAP}, install the RH-SSO adapter for {EAP} then configure {PRODUCT} application and the RH-SSO client adapter.

.Prerequisites
* RH-SSO is installed as described in <<sso-realm-proc>>.
* {PRODUCT} is installed in a {EAP} 7.1 server, as described in COMMENT: link to On Premise installation guide.

.Procedure
. Download the {EAP} adapter from the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html?product=core.service.rhsso&downloadType=distributions[Red Hat Customer Portal].
. Unzip and install the adapter. For installation instructions, see the https://access.redhat.com/documentation/en/red-hat-single-sign-on/7.0/securing-applications-and-services-guide/securing-applications-and-services-guide#jboss_adapter[JBoss EAP Adapter] section of the _Red Hat Single Sign On Securing Applications and Services Guide_.
. Go to `_EAP_HOME_/standalone/configuration` and open the `standalone.xml` and `standalone-full.xml` files. 
. Delete the `<single-sign-on/>` element from both of the files.
. Navigate to `_EAP_HOME_/standalone/configuration` directory in your {EAP} installation and edit the `standalone.xml` file to add the RH-SSO subsystem configuration. For example:
+
--
[source,xml]
----
<subsystem xmlns="urn:jboss:domain:keycloak:1.1">
 <secure-deployment name="decision-central.war">
   <realm>demo</realm>
   <realm-public-key>MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCrVrCuTtArbgaZzL1hvh0xtL5mc7o0NqPVnYXkLvgcwiC3BjLGw1tGEGoJaXDuSaRllobm53JBhjx33UNv+5z/UMG4kytBWxheNVKnL6GgqlNabMaFfPLPCF8kAgKnsi79NMo+n6KnSY8YeUmec/p2vjO2NjsSAVcWEQMVhJ31LwIDAQAB</realm-public-key>
   <auth-server-url>http://localhost:8180/auth</auth-server-url>
   <ssl-required>external</ssl-required>
   <enable-basic-auth>true</enable-basic-auth>
   <resource>kie</resource>
   <credential name="secret">759514d0-dbb1-46ba-b7e7-ff76e63c6891</credential>
   <principal-attribute>preferred_username</principal-attribute>
 </secure-deployment>
</subsystem>
----

In this example:

* `secure-deployment name` is the name of your application's WAR file.
* `realm` is the name of the realm that you created for the applications to use.
* `realm-public-key` is the public key of the realm you created. You can find the key in the *Keys* tab in the *Realm settings* page of the realm you created in the RH-SSO Admin Console. If you do not provide a value for `realm-public-key`, the server retrieves it automatically.
* `auth-server-url` is the  URL for the RH-SSO authentication server.
* `enable-basic-auth` is the  setting to enable basic authentication mechanism, so that the clients can use both token-based and basic authentication approaches to perform the requests.
* `resource` is the  name for the client that you created.
* `credential name` is the  secret key for the client you created. You can find the key in the *Credentials* tab on the *Clients* page of the RH-SSO Admin Console.
* `principal-attribute` is the login name of the user. If you do not provide this value, your User Id is displayed in the application instead of your user name.
+
[NOTE]
====
The RH-SSO server converts the user names to lowe rcase. Therefore, after integration with RH-SSO, your user name will appear in lower case in {PRODUCT}. If you have user names in upper case hard coded in business processes, the application may not be able to identify the upper case user.
====
--
+

. Navigate to `_EAP_HOME_/bin/` and enter the following command to start the {EAP} server:
+
--
[source]
----
./standalone.sh
----
--

[NOTE]
====
You can also configure the RH-SSO adapter for {EAP} by updating your application's WAR file to use the RH-SSO security subsystem. However, Red Hat recommends that you configure the adapter through the RH-SSO subsystem. Doing this updates the {EAP} configuration instead of applying the configuration on each WAR file.
====
